## Procesamiento de matrices (arreglos) con Numpy
Numpy is la biblioteca fundamental para el trabajo con computación científica en Python. Provee arreglos multidimencionales de altísima eficiencia y las herramientas para trabajar con estos arreglos. Para los familiarizados con Matlab, Numpy se utiliza de forma muy natural.

In [2]:
import numpy as np
np.__version__

'1.19.1'

### Crear arreglos desde listas

In [11]:
a = np.array([2, 3, 4])
print(a)
print(a.shape)
a.__class__

[2 3 4]
(3,)


numpy.ndarray

In [22]:
# acceder y cambiar valor
print(a[2])
a[2] = 9
print(a)

4
[2 3 9]


In [13]:
# arreglos de dos dimensiones
b = np.array([[2, 3, 4], [5, 6, 7]])
print(b)
print(b.shape)

[[2 3 4]
 [5 6 7]]
(2, 3)


In [25]:
# cambiar valor
b[1, 2] = 9
print(b)

[[2 3 4]
 [5 6 9]]


In [20]:
# o con 3 ...
c = np.array([[[2, 1, 2, 5], [4,2, 5, 2], [9, 8, 7, 6]], [[3,5, 4, 1], [8, 9, 2, 6], [0,1, 8, 8]]])
print(c)
print(c.shape)

[[[2 1 2 5]
  [4 2 5 2]
  [9 8 7 6]]

 [[3 5 4 1]
  [8 9 2 6]
  [0 1 8 8]]]
(2, 3, 4)


In [26]:
# cambiar valor
c[0, 0, 0] = 11
print(c)

[[[11  1  2  5]
  [ 4  2  5  2]
  [ 9  8  7  6]]

 [[ 3  5  4  1]
  [ 8  9  2  6]
  [ 0  1  8  8]]]


In [27]:
# hay que respetar las dimensiones
c[2, 3] = 8

IndexError: index 2 is out of bounds for axis 0 with size 2

## constructores de arreglos especiales

In [30]:
# arreglo vacio
a1 = np.zeros((3, 2))
print(a1)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [32]:
# unos
a2 = np.ones((2, 3))
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
# constante
a3 = np.full((3, 3), 3.14)
print(a3)

[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [36]:
# identidad
a4 = np.eye(3)
print(a4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [169]:
a5 = np.random.random((3, 2))
print(a5)

[[0.92154586 0.18799926]
 [0.06422019 0.1770903 ]
 [0.20795124 0.14558199]]


In [172]:
# Rangos
print(np.arange(2, 14))
print(np.arange(0, 50, 5))

[ 2  3  4  5  6  7  8  9 10 11 12 13]
[ 0  5 10 15 20 25 30 35 40 45]


## Indexado de arreglos

In [55]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a[2, 3]

12

In [58]:
# subarreglo
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [59]:
# Importante: No son nuevos arreglos, sino un acceso a subarreglos
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [60]:
b = a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [61]:
b[0, 0] = 55
print(a)
print(b)

[[ 1 55  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[55  3]
 [ 6  7]]


In [64]:
# Se puede mezclar el indexado entero con los rangos: se obtiene arreglo de menor rango
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [68]:
print(a[1, :])
print(a[1])

[5 6 7 8]
[5 6 7 8]


In [71]:
print(a[:,2])

[ 3  7 11]


In [72]:
print(a.shape)
print(a[2, :].shape)
print(a[:,2].shape)

(3, 4)
(4,)
(3,)


In [77]:
# Seleccion por arreglo de indices
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
print("***")
idxs = np.array([0, 2, 0, 1])
print(a[:,idxs])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
***
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [79]:
# Idem con filas
print(a[idxs, :])

[[1 2 3]
 [7 8 9]
 [1 2 3]
 [4 5 6]]


In [87]:
# Elementos por sus indices
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
idx1 = [0, 1, 2, 1]
idx2 = [2, 0, 1, 0]
a[idx1, idx2]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([3, 4, 8, 4])

In [88]:
# Igual se pueden modificar los elementos indizados ... recordar, es una submatriz del original ...
a[idx1, idx2] += 10
print(a)

[[ 1  2 13]
 [14  5  6]
 [ 7 18  9]
 [10 11 12]]


In [96]:
# Seleccion por el uso de arreglos booleanos
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
bool_idx = a % 2 == 0 
print(bool_idx)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[False  True False]
 [ True False  True]
 [False  True False]
 [ True False  True]]


In [97]:
# y ahora se utiliza el arreglo para hacer seleccionar
print(a[bool_idx])

[ 2  4  6  8 10 12]


In [98]:
# o para modificar
a[bool_idx] *= 2
print(a)

[[ 1  4  3]
 [ 8  5 12]
 [ 7 16  9]
 [20 11 24]]


In [249]:
# Noten que el arreglo booleano puede usarse en operaciones en otros arreglos
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.random.random((4, 3))
print(a)
print(b)
a[b < 0.5] += 19
print("***")
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[0.56683147 0.96341264 0.73766447]
 [0.59893821 0.33864254 0.29453928]
 [0.15718605 0.41056452 0.23695362]
 [0.27932737 0.51189733 0.35084025]]
***
[[ 1  2  3]
 [ 4 24 25]
 [26 27 28]
 [29 11 31]]


In [252]:
# Para utilizar multiples condiciones usar el operador & 
a[(b < 0.5) & (b > 0.2)]

array([24, 25, 27, 28, 29, 31])

In [229]:
# A los arreglos se les puede declarar el tipo de datos a utilizar. 
# Si no se pone, numpy elige uno compatible con los datos de inicializacion
x = np.array([1, 2])
print(x.dtype)
y = np.array([1.0, 2.0])
print(y.dtype)
z = np.array([True, False])
print(z.dtype)

int64
float64
bool


In [110]:
# Tambien se puede especificar el tipo
z = np.array([1, 2], dtype=np.float64)
print(z.dtype)
print(z)

float64
[1. 2.]


### Operaciones con arreglos

In [139]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [115]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [140]:
# Operaciones elemento a elemento
print(x-y)  # np.substract
print(x*y)  # np.multiply
print(x/y)  # np.divide
print(np.sqrt(x))
print(np.power(x, y))

# Muchas mas en: https://numpy.org/doc/stable/reference/routines.math.html

[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.0000e+00 6.4000e+01]
 [2.1870e+03 6.5536e+04]]


In [122]:
# Producto interno: dot
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

v.dot(w)

219

In [125]:
print(x)
print(v)
x.dot(v)

[[1 2]
 [3 4]]
[ 9 10]


array([29, 67])

In [127]:
print(x)
print(y)
x.dot(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [131]:
# Operaciones por ejes
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [134]:
# funcionan en matrices de mas dimensiones
x = np.array([[[2, 1, 2, 5], [4,2, 5, 2], [9, 8, 7, 6]], [[3,5, 4, 1], [8, 9, 2, 6], [0,1, 8, 8]]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))
print(np.sum(x, axis=2))

108
[[ 5  6  6  6]
 [12 11  7  8]
 [ 9  9 15 14]]
[[15 11 14 13]
 [11 15 14 15]]
[[10 13 30]
 [13 25 17]]


In [136]:
# Y se puede hacer por conjuntos de axis
print(np.sum(x, axis=(0,1)))
print(np.sum(x, axis=(0,2)))
print(np.sum(x, axis=(1, 2)))

[26 26 28 28]
[23 38 47]
[53 55]


In [141]:
# Traspuesta
x = np.array([[1,2,3], [4, 5, 6]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [228]:
# 'Stackeado' horizontal y vertical
a = np.array([[2, 3], [5, 6]])
b = np.array([[4, 3], [7, 9], [1, 6]])
c = np.array([[4, 5, 6], [7, 6, 5]])
print(np.vstack([a,b]))
print(np.hstack([a,c]))

[[2 3]
 [5 6]
 [4 3]
 [7 9]
 [1 6]]
[[2 3 4 5 6]
 [5 6 7 6 5]]


In [246]:
# where
a = np.array(range(0,10))
np.where(a > 5, a, a-5)

array([-5, -4, -3, -2, -1,  0,  6,  7,  8,  9])

In [247]:
# Si no se ponen valores para retornar, where retorna el indice de los True
np.where(a > 5)

(array([6, 7, 8, 9]),)

### Cambiando el shape de un arreglo
Nota: no cambia los valores ni su orden!

In [235]:
a = np.array(range(0, 24))
print(a)
print(a.shape)
b = a.reshape((2,12))
print(b)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
(2, 12)


In [240]:
# El total no puede tener mas ni menos elementos
a.reshape((3, 2))

ValueError: cannot reshape array of size 24 into shape (3,2)

In [241]:
# -1 calcula el tamaño correcto
a.reshape((3,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [242]:
a.reshape((-1, 6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [243]:
# -1 puede estar solamente en una dimension
a.reshape((-1, 2, -1))

ValueError: can only specify one unknown dimension

In [244]:
a.reshape((2, -1, 3))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

### Broadcasting
Este es un mecanismos para operar con arreglos de diferentes formas. 

In [143]:
# Ejemplo, sumarle un vector a cada fila de un arreglo
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # arreglo vacio con la misma estructura de ...

for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [147]:
# Solucion 2. Armar una nueva matriz repitiendo (v) en varias filas
vv = np.tile(v, (4, 1))
print(vv)
y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [149]:
# Bradcasting hace esto ultimo, de forma automatica
x+v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

**Reglas para el bradcasting**
- Si dos arreglos no tienen el mismo rango, adiciona 1 en su rangos a su shape hasta que se igualen

In [153]:
# Eso paso en el ejemplo anterior, pues
print(x.shape)
print(v.shape)

(4, 3)
(3,)


- Dos areglos son compatibles en una dimension si tienen el mismo tamaño, o uno de los arreglos tiene 1 en esa dimensión. 
En el ejemplo anterior, al adicionar 1 al shape de v, quedan compatibles: (4,3) y (1,3)
- Los arreglos pueden recibir broadcasting, si son compatibles en todas las dimensiones

In [156]:
# Compatibles
a = np.random.random((3, 4, 1))
b = np.random.random((3, 1, 4))
c = a+b

In [158]:
# Incompatibles
a = np.random.random((3, 4, 1))
b = np.random.random((3, 2, 4))
c = a+b

ValueError: operands could not be broadcast together with shapes (3,4,1) (3,2,4) 

- Luego del broadcasting, cada arreglo se comporta como si tuviera la shape de la máxima dimensión en cada rango

In [160]:
a = np.random.random((3, 4, 1))
b = np.random.random((1, 1, 5))
(a+b).shape

(3, 4, 5)

- Si en una dimensión un arreglo tiene un tamaño 1 y el otro arreglo mayor que 1, el primer arreglo se comporta como si se copiara múltiples veces en esa dimensión

In [163]:
a = np.ones((3, 4))
b = np.ones((3, 1))*3
print(a)
print(b)
a+b

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[3.]
 [3.]
 [3.]]


array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [166]:
a = np.ones((1, 4))
b = np.ones((3, 4))*5
print(a)
print(b)
a+b

[[1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [167]:
a = np.ones((1, 4))
b = np.ones((3, 1))*6
print(a)
print(b)
a+b

[[1. 1. 1. 1.]]
[[6.]
 [6.]
 [6.]]


array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [189]:
# Para saber el resultado de un broadcast (muy util para buscar errores):
print(np.broadcast_to(a, ((3,4))))
print(np.broadcast_to(b, ((3, 4))))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


Las funciones que soportan broadcasting se conocen como *funciones universales*. Estas incluyen todas las que hemos visto hasta ahora y muchas mas.

In [206]:
# Ejemplo, sumar una constante a un arreglo
a = np.random.random((4, 3))
print(a)
print(a + 4)

[[0.10412344 0.62840753 0.31716942]
 [0.99139931 0.6975653  0.58734823]
 [0.01972726 0.51369711 0.22250071]
 [0.37217875 0.38853473 0.25227575]]
[[4.10412344 4.62840753 4.31716942]
 [4.99139931 4.6975653  4.58734823]
 [4.01972726 4.51369711 4.22250071]
 [4.37217875 4.38853473 4.25227575]]


In [207]:
np.broadcast_to(4, (4, 3))

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [208]:
np.array(4).shape

()

In [224]:
# normalizar quitando la media a vectores
a = np.random.randint(1, 10, size=(4,3))
print(a)
mean = np.average(a, axis=0)
print(mean)
print(a - mean)
print(np.sum(a-mean))

[[1 1 3]
 [2 5 5]
 [5 4 5]
 [4 8 7]]
[3.  4.5 5. ]
[[-2.  -3.5 -2. ]
 [-1.   0.5  0. ]
 [ 2.  -0.5  0. ]
 [ 1.   3.5  2. ]]
0.0


In [225]:
# uniformizar una matriz de numeros con (x - min)/(max-min)
a = np.random.randint(1, 10, size=(4,3))
mx = np.max(a)
mn = np.min(a)
print(a)
print((a-mn)/(mx-mn))

[[5 2 1]
 [2 5 4]
 [1 1 8]
 [7 3 1]]
[[0.57142857 0.14285714 0.        ]
 [0.14285714 0.57142857 0.42857143]
 [0.         0.         1.        ]
 [0.85714286 0.28571429 0.        ]]


In [185]:
# Ejemplo, tabla de multiplicar
x = np.array(range(1, 11))
print(x)
x = x[:, np.newaxis]
print(x)
print(x.T)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [190]:
# y la tabla
x*x.T

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [198]:
# Ejemplo: matriz de distancias
coords = np.array([(2, 3), (4, 5), (-1,8), (0, 3)])
x1 = coords[:, np.newaxis, :]
x2 = coords[np.newaxis, :, :]
print(x1)

[[[ 2  3]]

 [[ 4  5]]

 [[-1  8]]

 [[ 0  3]]]


In [200]:
print(x2)

[[[ 2  3]
  [ 4  5]
  [-1  8]
  [ 0  3]]]


In [205]:
print(x1.shape)
print(x2.shape)

(4, 1, 2)
(1, 4, 2)


In [204]:
np.sqrt(np.sum((x1 - x2)**2, axis=-1))

array([[0.        , 2.82842712, 5.83095189, 2.        ],
       [2.82842712, 0.        , 5.83095189, 4.47213595],
       [5.83095189, 5.83095189, 0.        , 5.09901951],
       [2.        , 4.47213595, 5.09901951, 0.        ]])