# Ejercicios

In [ ]:
# 0. Crear un arreglo de una dimension con los numeros de 0 a 9


In [ ]:
# 1. Crear un arreglo booleano de 3x3 con todos los valores en True


In [ ]:
# 2. Extraer todos los numeros impares de un arreglo de 1D
arr = np.arange(0,10)


In [ ]:
# 3. Reemplace todos los numeros negativos por 33
arr = np.random.randint(-10, 10, size=(10))


In [ ]:
# 4. Reemplace todos los numeros positivos por -5, pero sin cambiar el arreglo original
arr = np.random.randint(-10, 10, size=(10))


In [ ]:
# 5. Convierta un arreglo 1D con los numeros del 1 al 10 en otro 2D con dos filas


In [ ]:
# 6. Apile dos de estos arreglos horizontal y dos verticalmente
a = np.ones((3, 2))
b = np.ones((4, 2)) * 2
c = np.ones((3, 5)) * 3


In [ ]:
# 7. A partir del arreglo 
a = np.array([1, 2, 3])
# Genere el arreglo 
out = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
# Utilizando solamente funciones de numpy y 'a'


In [ ]:
# 9. Obtener la posicion donde estos arreglos coinciden
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


In [ ]:
# 10. Obtenga del siguiente arreglo un subarreglo con los valores entre 5 y 10, ambos incluidos
a = np.array([2, 6, 1, 9, 10, 3, 27])


In [ ]:
# 11. Intercambie la primera y segunda fila del siguiente arreglo
arr = np.arange(9).reshape(3,3)


In [ ]:
# 12. Intercambie las dos últimas columnas del siguiente arreglo
arr = np.arange(9).reshape(3,3)


In [ ]:
# 13. Invierta las filas del siguiente arreglo
arr = np.arange(16).reshape(4,4)


In [ ]:
# 14. Invierta las columnas del siguiente arreglo
arr = np.arange(16).reshape(4,4)


In [ ]:
# 15. Crea un arreglo 2d de 10x10 con 1 en el borde y 0 adentro


In [ ]:
# 16. Crea un borde de valores 0 alrededor del siguiente arreglo 2d
a = np.arange(9).reshape(3,3)


In [ ]:
# 17. Crear una matriz de 5x5 con valores 1, 2, 3, ... justo debajo de la diagonal


In [ ]:
# 18. Cree un patron de tablero de ajedrez de 8x8


In [ ]:
# 19. Crear un patrón de tablero de ajedrez usando tile


In [ ]:
# 20. Normalizar un arreglo aleatorio de 5x5
arr = np.random.random((5,5))


In [ ]:
# 21. Realice el producto de una matriz de 5x3 con otra de 3x2


In [ ]:
# 22. En un arreglo 1D, halle el opuesto de todos los elementos entre 3 y 8
arr = np.arange(1, 14)


In [ ]:
# 23. Cree una matriz de 5x5 con valores en las filas del 1 al 4


In [ ]:
# 24. Cree un vector de tamaño 10 con valores x-distantes entre 0 y 1, ambos excluidos.


In [ ]:
# Hay una función para eso ...
np.linspace(0,1,11,endpoint=False)[1:]

In [ ]:
# 25. Considere un arreglo aleatorio de 10x2 con coordenadas cartesianas. Conviertalo a coordenadas polares
cart = np.random.random((10,2))


In [ ]:
# 26. Cree un vector aleatorio de tamaño 10 y substituya el valor máximo por 0
# hint: np.argmax


In [ ]:
# 27. Encuentre el valor mas cercano a un valor dado en un vector


In [ ]:
# 28. Construya un arreglo de posiciones x,y que cubran el area [0,1]x[0,1]


In [ ]:
# 29. Dado un arreglo de 4 dimensiones, conviertalo en un arreglo de 3 dimensiones colapsando las dos ultimas en 1
arr = np.arange(48).reshape((2, 3, 4, 2))


In [ ]:
# 30. Considere el vector [1,2,3,4,5]. Como hacemos un nuevo vector insertando 3 ceros consecutivos 
# entre cada uno de estos valores
x = np.array([1, 2, 3, 4, 5])


## Soluciones

In [7]:
import numpy as np
# Crear un arreglo de una dimension con los numeros de 0 a 9
print(np.arange(0,10))
print(np.array(range(0,10)))
print(np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [8]:
# 1. Crear un arreglo booleano de 3x3 con todos los valores en True
print(np.full((3,3), True, dtype=np.bool))
print(np.zeros((3,3)) == 0)
print(np.ones((3,3), dtype=np.bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


/home/milton/miniconda3/envs/mlbase/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  
/home/milton/miniconda3/envs/mlbase/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


In [17]:
# 2. Extraer todos los numeros impares de un arreglo de 1D
arr = np.arange(0,10)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [20]:
arr = np.arange(5)
arr[[True, False, True, True, False]]

array([0, 2, 3])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# 3. Reemplace todos los numeros negativos por 33
arr = np.random.randint(-10, 10, size=(10))
print(arr)
arr[arr < 0] = 33
print(arr)

[-10  -6   7  -1   7   6   2  -5  -5  -3]
[33 33  7 33  7  6  2 33 33 33]


In [ ]:
# 4. Reemplace todos los numeros positivos por -5, pero sin cambiar el arreglo original
arr = np.random.randint(-10, 10, size=(10))
print(arr)
np.where(arr > 0, -5, arr)

In [24]:
# 5. Convierta un arreglo 1D con los numeros del 1 al 10 en otro 2D con dos filas
a = np.arange(1, 11)
a.reshape((-1, 5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
# 6. Apile dos de estos arreglos horizontal y dos verticalmente
a = np.ones((3, 2))
b = np.ones((4, 2)) * 2
c = np.ones((3, 5)) * 3
print(np.hstack([a, c]))
print(np.vstack([a, b]))

[[1. 1. 3. 3. 3. 3. 3.]
 [1. 1. 3. 3. 3. 3. 3.]
 [1. 1. 3. 3. 3. 3. 3.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]]


In [ ]:
# 7. A partir del arreglo 
a = np.array([1, 2, 3])
# Genere el arreglo 
out = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
# Utilizando solamente funciones de numpy y 'a'
np.hstack([
    np.vstack([a, a, a]).T.reshape((1, -1))[0],
    a, a, a])

In [ ]:
# 8. Todo lo que parece complicado, hay una forma mejor de hacerlo
np.r_[np.repeat(a,3), np.tile(a, 3)]

In [26]:
# 9. Obtener la posicion donde estos arreglos coinciden
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [27]:
# 10. Obtenga del siguiente arreglo un subarreglo con los valores entre 5 y 10, ambos incluidos
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[np.where((5 <= a) & (a <= 10))]

array([ 6,  9, 10])

In [29]:
# 11. Intercambie la primera y segunda fila del siguiente arreglo
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,0,1, 0, 2], :]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1, 2],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [31]:
# 12. Intercambie las dos últimas columnas del siguiente arreglo
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, [0, 1]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[0, 1],
       [3, 4],
       [6, 7]])

In [5]:
# 13. Invierta las filas del siguiente arreglo
arr = np.arange(16).reshape(4,4)
print(arr)
arr[np.arange(3, -1, -1), :]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [34]:
# Otra, mas simple
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [6]:
# 14. Invierta las columnas del siguiente arreglo
arr = np.arange(16).reshape(4,4)
print(arr)
arr[:,::-1]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [36]:
# 15. Crea un arreglo 2d con 1 en el borde y 0 adentro
def cuad(size):
    a = np.ones(size)
    a[1:-1,1:-1] = 0
    return a

cuad((4, 8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
# 16. Crea un borde de valores 0 alrededor de un arreglo 2d
a = np.arange(9).reshape(3,3)
print(a)
r,c = a.shape
b = np.zeros((r+2, c+2))
b[1:-1, 1:-1] = a
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 3. 4. 5. 0.]
 [0. 6. 7. 8. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# Como siempre, hay algo mas simple ...
np.pad(a, pad_width=1, mode='constant', constant_values=0)

In [ ]:
# 17. Crear una matriz de 5x5 con valores 1, 2, 3, ... justo debajo de la diagonal
a = np.zeros((5, 5))
for idx in range(4):
    a[idx+1, idx] = idx + 1
a

In [ ]:
# Forma mas simple
np.diag([1, 2, 3, 4], k=-1)

In [45]:
(np.arange(0,81).reshape((9,-1)) % 2)[:8,:8]

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [47]:
np.arange(0,81).reshape((9,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [48]:
# 18. Cree un patron de tablero de ajedrez de 8x8
a = np.ones((8,8))
a[::2,::2] = 0
a[1::2,1::2]=0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [ ]:
# 19. Crear un patrón de tablero de ajedrez usando tile
np.tile([1, 0], 36).reshape((-1, 9))[:, :-1]

In [ ]:
# otra solucion

In [ ]:
np.tile([[0, 1],[1,0]], (4,4))

In [ ]:
# 20. Normalizar un arreglo aleatorio de 5x5
arr = np.random.random((5,5))
m = np.mean(arr)
st = np.std(arr)
norm = (arr - m)/st
print(norm)
print(sum(sum(norm)))

In [ ]:
# 21. Realice el producto de una matriz de 5x3 con otra de 3x2
np.ones((5,3)).dot(np.ones((3, 2)))

In [ ]:
# 22. En un arreglo 1D, halle el opuesto de todos los elementos entre 3 y 8
arr = np.arange(1, 14)
arr[(arr >= 3)&(arr <=8)] *= -1
arr

In [ ]:
# 23. Cree una matriz de 5x5 con valores en las filas del 1 al 4
arr = np.zeros((5, 5))
arr + np.arange(5)

In [ ]:
# sin broadcast
np.tile(np.arange(5), (5,1))

In [ ]:
# 24. Cree un vector de tamaño 10 con valores x-distantes entre 0 y 1, ambos excluidos.
(np.arange(0,11)*(1/11))[1:-1]

In [49]:
# Hay una función para eso ...
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
# 25. Considere un arreglo aleatorio de 10x2 con coordenadas cartesianas. Conviertalo a coordenadas polares
cart = np.random.random((10,2))
x, y = cart[:,0], cart[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y, x)
print(cart)
np.hstack([r[:,np.newaxis], t[:, np.newaxis]])

In [ ]:
# 26. Cree un vector aleatorio de tamaño 10 y substituya el valor máximo por 0
# hint: np.argmax
v = np.random.random(10)
v[np.argmax(v)] = 0
v

In [ ]:
# 27. Encuentre el valor mas cercano a un valor dado en un vector
arr = np.random.randint(0,100, size=(20))
v = 15
print(arr)
arr[np.argmin(np.abs(arr - v))]

In [ ]:
# 28. Construya un arreglo de posiciones x,y que cubran el area [0,1]x[0,1]
delta = 5
import itertools as it
np.array(list(it.product(range(0,delta), range(0, delta)))) / (delta - 1)

In [ ]:
# Hay una función para esto ...
delta = 5
x, y = np.meshgrid(np.linspace(0,1,delta), np.linspace(0,1,delta))
x,y
# note que esta función devuelve cada coordenada en un arreglo independiente, y de forma comoda para graficar

In [ ]:
np.sin(x**2 + y**2)

In [ ]:
# 29. Dado un arreglo de 4 dimensiones, conviertalo en un arreglo de 3 dimensiones colapsando las dos ultimas en 1
arr = np.arange(48).reshape((2, 3, 4, 2))
print(arr)
arr2 = arr.reshape(arr.shape[:-2]+(-1,))
print(arr2)

In [ ]:
# 30. Considere el vector [1,2,3,4,5]. Como hacemos un nuevo vector insertando 3 ceros consecutivos 
# entre cada uno de estos valores
x = np.array([1, 2, 3, 4, 5])
nz = 6
np.hstack([x[:,np.newaxis], np.zeros((5, nz))]).reshape((1,-1))

In [ ]:
# otra solución
result = np.zeros(len(x)+(len(x)-1)*nz)
result[::nz+1] = x
result